[ADDED/MODIFIED] Initial Commit for implementing named bounds for ele…
ls1intum/Apollon pull request #210
Opened 2022-03-21 09:44 UTC by minrows

…ments

### Checklist
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes
- [ ] I translated all the newly inserted strings into German and English

### Motivation and Context

### Description

### Steps for Testing

1. ...

### Screenshots

2022-03-22 08:23 UTC, martindevtum commented on src/main/packages/flowchart/flowchart-decision/flowchart-decision.tsx
> +    this.bounds = namedBounds;
I would personally skip the creation of the constant and just assign to this.bounds directly, as we are not using namedBounds anywhere else

2022-03-23 08:57 UTC, martindevtum commented on src/main/utils/name-bounds.ts
> +export function calculateNameBounds(element: any, layer: ILayer) {
shouldn't we add the return type IBoundary here?

2022-03-23 09:06 UTC, martindevtum requested changes
I would also like it if you would use the newly created name bounds function to already existing usages of nameBounds. 

It is for example used in uml-package.ts, please calculate the nameBounds here with our new function. 
This might be the only occurence, but please just. double check it again.


Other than that, it is working nicely.

2022-03-23 15:00 UTC, bassner commented
I tested this locally and it seems to work well, except for packages (class diagram), which can still cut off their text content vertically:
![grafik](https://user-images.githubusercontent.com/23171488/159729124-f259d9ed-c632-4a6f-bf11-0d812cf121b0.png)
But I'm not 100% sure if that was even the point of this PR or if it was just about keep the correct width on certain objects?

2022-03-23 16:20 UTC, minrows commented
> 

Done. Minimum height is now calculated based on the name as well.

2022-03-23 16:59 UTC, bassner approved these changes
LGTM!

2022-03-24 08:05 UTC, martindevtum commented
looking good

2022-03-24 08:05 UTC, martindevtum approved these changes

2022-03-30 11:16 UTC, merged