Bugfix/darkmode color issue
ls1intum/Apollon pull request #242
Opened 2022-06-08 18:25 UTC by minrows

### Checklist
- [x] I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Color selector and elements separators of Apollon were not adapted for dark mode.

### Description
This PR fixes the issue with an adaptation of dark mode in the Color selector and elements separator of Apollon.

### Screenshots
**1. Separator (Before)**
![image](https://user-images.githubusercontent.com/14681902/172685517-b949267c-f443-47ca-af5b-3a8f0dbc857e.png)
**2. Separator (After)**
![image](https://user-images.githubusercontent.com/14681902/172685808-3bc4ce41-5f71-4ebf-8a42-07b176a17637.png)
**3. Color Selector (Before)**
![image](https://user-images.githubusercontent.com/14681902/172689385-55305b26-68f1-49eb-89da-843229fbeed0.png)
**4. Color Selector (After)**
![image](https://user-images.githubusercontent.com/14681902/172689305-67f90269-38d4-4569-87bf-9e4ef3e1e617.png)

2022-06-12 13:18 UTC, minrows commented
PR now deployed to [test server](https://test1.apollon.ase.in.tum.de/).

2022-06-13 08:32 UTC, canberkanar requested changes
Tested on Apollon Test Server. The changes look good to me. However, there is a minor design-related inconsistency I realized. For input fields in dark mode, there is a slight color variation with respect to the background however when we are in the light mode, there are no differences. IMO using a slightly different color here would make the input fields more noticeable. Please take a look at the screenshots below.

![image](https://user-images.githubusercontent.com/67344158/173312439-e4c1fb96-1f04-4366-981f-a2037dcf745f.png)
![image](https://user-images.githubusercontent.com/67344158/173312527-c4fc6221-8924-47bc-8e1a-c8d8bc22f140.png)

2022-06-13 08:37 UTC, canberkanar approved these changes

2022-06-13 08:43 UTC, canberkanar requested changes
Sorry just realized these elements are not styled properly for dark mode.

![image](https://user-images.githubusercontent.com/67344158/173314510-54ae9557-b469-4c60-952e-0cb7a64808dc.png)
![image](https://user-images.githubusercontent.com/67344158/173314908-b4f7c3b2-7057-42c4-bc71-8c95b62c0ef2.png)
![image](https://user-images.githubusercontent.com/67344158/173315000-674f3580-c28d-4d12-9b18-827b052cf594.png)

2022-06-13 09:46 UTC, minrows commented
Thanks @canberkanar for the feedback.

- Out of 4 suggestions 3 are implemented. 
- One regarding the blue selector is not changed, as it seems to be the case for Artemis too. 

PS: These changes are needed to made on [Standalone PR](https://github.com/ls1intum/Apollon_standalone/pull/36)

2022-06-13 09:59 UTC, canberkanar approved these changes
Retested on Apollon Test Server one. All issues I mentioned were fixed. Thanks for your quick response.

2022-06-13 12:16 UTC, merged