UI Changes to Control Panel
ls1intum/Apollon pull request #298
Opened 2023-08-03 14:09 UTC by AlexanderG2207

### Checklist
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes
- [x] I translated all the newly inserted strings into German and English

### Motivation and Context
1. When scrolling between the elements of the switches in the control panel, there is no border on the left side of the middle elements. 
2. When switching between Light and Dark Mode there is the obvious indicator of the change, which is the editor changing its color. However, there is no indication on the Light/Dark switch buttons itself.

### Description
1. By removing the "border-left" property from the switch styles, the left border of the element is normal and the change between switch elements looks cleaner.
2. By clicking one of the Light/Dark switches, the `setThemings()` function is called, which takes a string of the button that was clicked. The function then adds the "selected" style property to the selected button and removes the "selected" style property from the unselected one.

### Steps for Testing
1. Run Apollon locally.
2. Open Apollon in Chrome.
3. Check if the borders transition well on the switches when moving between them.
4. Check if the button is selected when changing between light and dark mode.

### Screenshots
### Before:
![Before](https://github.com/ls1intum/Apollon/assets/40467337/3598c73d-d412-4a89-9dbe-99b157ab791e)

### After:
![After](https://github.com/ls1intum/Apollon/assets/40467337/9191895f-e7cc-471b-9416-6bc4f9035d3c)

2023-08-30 14:31 UTC, loreanvictor commented
down the line, perhaps the control panel should be switched from static HTML / JS to a proper React component, but I feel that falls beyond the scope of this PR.

2023-08-30 14:31 UTC, loreanvictor approved these changes

2023-08-31 21:08 UTC, florian-glombik reviewed
The change itself looks fine and works for me on the local setup, however, it just works after adjusting `_getNewSubscriptionId` in `apollon-editor.ts` to use a radix in `parseInt`

Can you reproduce the same issue? - If yes It would be great to just fix it right away!
_Otherwise I am pretty confused as to why it only appears to be an issue for me when checking out bef2b891d33e4b5e4b778829cbaa9e4b82931ae7_

I would also welcome the change to a tsx component, but agree that it can be done within another PR :)

2023-08-31 21:44 UTC, florian-glombik requested changes
It seems like a test needs to be fixed

```
Summary of all failing tests
FAIL src/tests/unit/apollon-editor-test.tsx (96.662 s)
  ● test apollon editor  › exportModelAsSvg

    TypeError: Cannot read properties of null (reading 'outerHTML')

      105 |
      106 |     return {
    > 107 |       svg: replaceColorVariables(container.querySelector('svg')!.outerHTML),
          |                                                                 ^
      108 |       clip: svg.state.bounds,
      109 |     };
      110 |   }
```

2023-09-03 12:56 UTC, merged